# Docker compose file for the Flex environment

services:
  #database section
  securitiesdb:
    image: container-registry.oracle.com/database/free:23.5.0.0-lite
  redisdb:
    image: redis:7-alpine
  mongodb:
    image: mongo:6.0
  
  #infrastructure section
  portainer:
    image: portainer/portainer-ce:2.27.2
  vault:
    image: hashicorp/vault:1.15.4
  #service section

#network section
networks:
  flex-network:
    driver: bridge

#volumes section
volumes:
  portainer_data:
    name: portainer_data
  securitiesdb_data:
    name: securitiesdb_data
  redisdb_data:
    name: redisdb_data
  mongodb_data:
    name: mongodb_data
  vault_data:
    name: vault_data
