# Docker compose file for the Flex environment

services:
  #database section
  securitiesdb:
    image: container-registry.oracle.com/database/free:23.5.0.0-lite
  redisdb:
    image: redis:7-alpine
  mysql:
    image: mysql:8.4.5
  # mongodb:
  #   image: mongo:6.0
  
  #infrastructure section
  portainer:
    image: portainer/portainer-ce:2.27.2
  #service section

#volumes section
volumes:
  portainer_data:
    name: portainer_data
  securitiesdb_data:
    name: securitiesdb_data
  redisdb_data:
    name: redisdb_data
  mysql_data:
    name: mysql_data
  # mongodb_data:
  #   name: mongodb_data
