# Docker compose file for the Flex environment

services:
  #database section
  securitiesdb:
    image: container-registry.oracle.com/database/free:23.5.0.0-lite
  redisdb:
    image: redis:7-alpine
  
  #infrastructure section
  portainer:
    image: portainer/portainer-ce:2.27.2
  ollama:
    image: ghcr.io/ollama/ollama:latest
  #service section

#volumes section
volumes:
  portainer_data:
    name: portainer_data
  securitiesdb_data:
    name: securitiesdb_data
  redisdb_data:
    name: redisdb_data
  ollama_data:
    name: ollama_data
  # mongodb_data:
  #   name: mongodb_data
