version: '3.8'

services:
  #database section
  accountdb:
    container_name: accountdb
    environment:
      - ACCEPT_ORACLE_LICENSE=yes
      - ORACLE_SID=FREE
      - ORACLE_PDB=ORCLPDB1
      - ORACLE_PWD=Luyenhaidang10062002@
    ports:
      - "1521:1521"
      - "5500:5500"
    volumes:
      - oracle_data:/opt/oracle/oradata

  productdb:
    container_name: productdb
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "Luyenhaidang10062002@"
      MYSQL_DATABASE: "ProductDB"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "Luyenhaidang10062002@"
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  customerdb:
    container_name: customerdb
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "Luyenhaidang10062002@"
      POSTGRES_DB: "CustomerDb"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  basketdb:
    container_name: basketdb
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  #infrastructure section
  portainer:
    container_name: portainer
    ports:
      - "9000:9000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
  pgadmin:
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "luyenhaidangit@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "Luyenhaidang10062002@"
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin

  #service section
