version: '3.8'

services:
  #database section
  productdb:
    image: mysql:8.1.0
  customerdb:
    image: postgres:15-alpine
  basketdb:
    image: redis:7-alpine
  
  #infrastructure section
  portainer:
    image: portainer/portainer-ce:2.22.0
  pgadmin:
    image: dpage/pgadmin4:8.13

  #service section

#network section
networks:
  flex-network:
    driver: bridge

#volumes section
volumes:
  portainer_data:
    name: portainer_data
  mysql_data:
    name: mysql_data
  pgadmin_data:
    name: pgadmin_data
  postgres_data:
    name: postgres_data
