version: '3.8'

services:
  #database section
  
  #infrastructure section
  portainer:
    image: portainer/portainer-ce:2.22.0

  #service section

#network section
networks:
  flex-network:
    driver: bridge

#volumes section
volumes:
  portainer_data:
    name: portainer_data
