# This file is used to override the default docker-compose.yml file

services:
  #database section
  # securitiesdb:
  #   container_name: securitiesdb
  #   environment:
  #     - ACCEPT_ORACLE_LICENSE=yes
  #     - ORACLE_SID=FREE
  #     - ORACLE_PDB=ORCLPDB1
  #     - ORACLE_PWD=haidang106
  #   ports:
  #     - "1521:1521"
  #   volumes:
  #     - securitiesdb_data:/opt/oracle/oradata

  redisdb:
    container_name: redisdb
    ports:
      - "6379:6379"
    volumes:
      - redisdb_data:/data
    command: ["redis-server", "--requirepass", "Luyenhaidang10062002@"]
    environment:
      - REDIS_PASSWORD=Luyenhaidang10062002@

  sqlserverdb:
    container_name: sqlserverdb
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdb_data:/var/opt/mssql
    environment:
      ACCEPT_EULA: "1"
      MSSQL_SA_PASSWORD: "MyStrongPass123"
      MSSQL_PID: "Developer"
      MSSQL_USER: "SA"

  # mongodb:
  #   container_name: mongodb
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME=admin
  #     - MONGO_INITDB_ROOT_PASSWORD=admin123
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongodb_data:/data/db

  #infrastructure section
  portainer:
    container_name: portainer
    ports:
      - "9000:9000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  jenkins:
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
    environment:
      - JENKINS_OPTS=--prefix=/jenkins
  #service section
