version: '3.8'

services:
  #database section
  securitiesdb:
    image: container-registry.oracle.com/database/free:23.5.0.0-lite
  investordb:
    image: container-registry.oracle.com/database/free:23.5.0.0-lite
  systemdb:
    image: container-registry.oracle.com/database/free:23.5.0.0-lite
  orderingdb:
    image: container-registry.oracle.com/database/free:23.5.0.0-lite
  basketdb:
    image: redis:7-alpine
  
  #infrastructure section
  portainer:
    image: portainer/portainer-ce:2.22.0

  #service section

#network section
networks:
  flex-network:
    driver: bridge

#volumes section
volumes:
  portainer_data:
    name: portainer_data
  securitiesdb_data:
    name: securitiesdb_data
  investordb_data:
    name: investordb_data
  systemdb_data:
    name: systemdb_data
  orderingdb_data:
    name: orderingdb_data
  basketdb_data:
    name: basketdb_data
